sudo: false
language: rust
cache: cargo
os:
  - linux
  - windows

rust:
  - stable

# NOTE: disable Travis' cache for now because it makes the Windows build fail
cache:
  directories:

before_script:
  - rustup component add rustfmt-preview clippy

script:
  - '[ "$TRAVIS_BRANCH" != master ] && [ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ] && rustfmt --check **/*.rs'
  - '[ "$TRAVIS_BRANCH" != master ] && [ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ] && cargo clippy --all-targets --all-features -- -D warnings'
  - cargo build
  - cargo test
  - cargo doc
