sudo: false
language: rust
cache: cargo
os:
  - linux
  - windows

rust:
  - stable

# NOTE: disable Travis' cache for now because it makes the Windows build fail
cache:
  directories:

script:
  - 'if [ "$TRAVIS_BRANCH" != master ] && [ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ]; then rustfmt --check **/*.rs; fi'
  - 'if [ "$TRAVIS_BRANCH" != master ] && [ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ]; then cargo clippy --all-targets --all-features -- -D warnings; fi'
  - cargo build
  - cargo test
  - cargo doc
