language: rust
os:
  - linux
  - windows

rust:
  - stable

# NOTE: disable Travis' cache for now because it makes the Windows build fail
cache:
  directories:

before_script:
  - rustup component add rustfmt-preview clippy

script:
  - 'if [ -n "$TRAVIS_PULL_REQUEST" ]; then rustfmt --check **/*.rs; fi'
  - 'if [ -n "$TRAVIS_PULL_REQUEST" ]; then cargo clippy --all-targets --all-features -- -D warnings; fi'
  - cargo build
  - cargo test
  - cargo doc
