sudo: false
language: rust
cache: cargo

rust:
  - stable

before_script:
  - rustup component add rustfmt-preview clippy

script:
  - |
      rustfmt --check **/*.rs &&
      cargo clippy --all-targets --all-features &&
      cargo build &&
      cargo test &&
      cargo bench &&
      cargo doc
