[package]
name = "gptman"
version = "0.1.0"
authors = ["Cecile Tonglet <cecile.tonglet@cecton.com>"]
license = "MIT"
edition = "2018"
description = "A GPT manager that allows you to copy partitions from one disk to another"
repository = "https://github.com/cecton/gptman"
homepage = "https://github.com/cecton/gptman"
readme = "README.md"
keywords = ["gpt", "partition", "table", "filesystem", "disk"]
categories = ["command-line-utilities"]

[[bin]]
name = "gptman"
path = "src/cli/main.rs"
doc = false

[lib]
name = "gptman"

[badges]
travis-ci = { repository = "cecton/gptman" }
is-it-maintained-issue-resolution = { repository = "cecton/gptman" }
is-it-maintained-open-issues = { repository = "cecton/gptman" }
maintenance = { status = "actively-developed" }

[dependencies]
bincode = "1.0.1"
serde_derive = "1.0.83"
serde = "1.0.83"
crc = "1.0.0"

[features]
default = [ "cli" ]
cli = [ "lazy_static", "ansi_term", "pad", "unicode-width", "clap", "linefeed", "nix", "rand", "structopt" ]

[dependencies.lazy_static]
version = "1.2.0"
optional = true
default-features = false

[dependencies.ansi_term]
version = "0.11"
optional = true
default-features = false

[dependencies.pad]
version = "0.1"
optional = true
default-features = false

[dependencies.unicode-width]
version = "0.1.5"
optional = true
default-features = false

[dependencies.clap]
version = "2.32"
optional = true
default-features = false

[dependencies.linefeed]
version = "0.5.0"
optional = true
default-features = false

[dependencies.nix]
version = "0.12.0"
optional = true
default-features = false

[dependencies.rand]
version = "0.5.5"
optional = true
default-features = false

[dependencies.structopt]
version = "0.2"
optional = true
default-features = false
