[package]
name = "gptman"
version = "0.7.0"
authors = ["Cecile Tonglet <cecile.tonglet@cecton.com>"]
license = "MIT"
edition = "2018"
description = "A GPT manager that allows you to copy partitions from one disk to another"
repository = "https://github.com/cecton/gptman"
homepage = "https://github.com/cecton/gptman"
documentation = "https://docs.rs/gptman"
readme = "README.md"
exclude = ["/.gitignore", "/.travis.yml"]
keywords = ["gpt", "partition", "table", "filesystem", "disk"]
categories = ["command-line-utilities"]

[[bin]]
name = "gptman"
path = "src/cli/main.rs"
doc = false
required-features = ["cli"]

[lib]
name = "gptman"

[badges]
travis-ci = { repository = "cecton/gptman" }
is-it-maintained-issue-resolution = { repository = "cecton/gptman" }
is-it-maintained-open-issues = { repository = "cecton/gptman" }
maintenance = { status = "actively-developed" }

[dependencies]
bincode = "1.3.1"
serde = { version = "1.0.116", features = ["derive"] }
crc = "1.0.0"
err-derive = "0.2.4"
lazy_static = { version = "1.2.0", optional = true }
ansi_term = { version = "0.12", optional = true }
pad = { version = "0.1", optional = true }
unicode-width = { version = "0.1.8", optional = true }
clap = { version = "2.33", optional = true }
linefeed = { version = "0.6.0", optional = true }
rand = { version = "0.7", optional = true }
structopt = { version = "0.3", optional = true }

[features]
default = [ "cli" ]
cli = [ "lazy_static", "ansi_term", "pad", "unicode-width", "clap", "linefeed", "rand", "structopt" ]

[target.'cfg(target_os = "linux")'.dependencies]
nix = "0.18"
